export default [
    'node_modules', 'out', 'target',
    '.pnpm',
    '.next',
    '.yarn',
    '.git',
    '.vs',
    '.fleet',
    '*.json',
    '*.jpg',
    '*.jpeg',
    '*.png',
    '*.ico',
    '*.woff*',
    '*.ttf',
    '*.wrm',
    '*.map',
    '*.svg',
    '*.ai',
    'yarn.lock',
    'pnpm-lock.yaml',
    'package-lock.json'
]